'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace SessionService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SessionServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class SessionService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/SessionService/SessionService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearSession", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ClearSession(ByVal UserId As String, ByVal Password As String, ByVal DOB As String, ByVal SchoolName As String) As String
            Dim results() As Object = Me.Invoke("ClearSession", New Object() {UserId, Password, DOB, SchoolName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginClearSession(ByVal UserId As String, ByVal Password As String, ByVal DOB As String, ByVal SchoolName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearSession", New Object() {UserId, Password, DOB, SchoolName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndClearSession(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearPassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ClearPassword(ByVal UserId As String, ByVal DOB As String, ByVal SchoolName As String) As String
            Dim results() As Object = Me.Invoke("ClearPassword", New Object() {UserId, DOB, SchoolName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginClearPassword(ByVal UserId As String, ByVal DOB As String, ByVal SchoolName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearPassword", New Object() {UserId, DOB, SchoolName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndClearPassword(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChangePassword(ByVal UserId As String, ByVal OldPassword As String, ByVal NewPassword As String) As String
            Dim results() As Object = Me.Invoke("ChangePassword", New Object() {UserId, OldPassword, NewPassword})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginChangePassword(ByVal UserId As String, ByVal OldPassword As String, ByVal NewPassword As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChangePassword", New Object() {UserId, OldPassword, NewPassword}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndChangePassword(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServerTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetServerTime() As String
            Dim results() As Object = Me.Invoke("GetServerTime", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetServerTime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetServerTime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetServerTime(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreSettings", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StoreSettings(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal Settings As String) As String
            Dim results() As Object = Me.Invoke("StoreSettings", New Object() {UserId, PasswordChallenge, Settings})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStoreSettings(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal Settings As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StoreSettings", New Object() {UserId, PasswordChallenge, Settings}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStoreSettings(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadSettings", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadSettings(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("LoadSettings", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginLoadSettings(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoadSettings", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLoadSettings(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreIPAddress", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StoreIPAddress(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal IpAddress As String) As String
            Dim results() As Object = Me.Invoke("StoreIPAddress", New Object() {UserId, PasswordChallenge, IpAddress})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStoreIPAddress(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal IpAddress As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StoreIPAddress", New Object() {UserId, PasswordChallenge, IpAddress}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStoreIPAddress(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreBackMessage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StoreBackMessage(ByVal Messages As String) As String
            Dim results() As Object = Me.Invoke("StoreBackMessage", New Object() {Messages})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStoreBackMessage(ByVal Messages As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StoreBackMessage", New Object() {Messages}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStoreBackMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
