'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace VoteService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VoteServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class VoteService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/voteService/VoteService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendVoteMessage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendVoteMessage(ByVal SenderId As String, ByVal PasswordChallenge As String, ByVal GroupId As String, ByVal Message As String) As String
            Dim results() As Object = Me.Invoke("SendVoteMessage", New Object() {SenderId, PasswordChallenge, GroupId, Message})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendVoteMessage(ByVal SenderId As String, ByVal PasswordChallenge As String, ByVal GroupId As String, ByVal Message As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendVoteMessage", New Object() {SenderId, PasswordChallenge, GroupId, Message}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendVoteMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MyVote", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MyVote(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal MessageId As String, ByVal VoteString As String) As String
            Dim results() As Object = Me.Invoke("MyVote", New Object() {UserId, PasswordChallenge, MessageId, VoteString})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginMyVote(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal MessageId As String, ByVal VoteString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MyVote", New Object() {UserId, PasswordChallenge, MessageId, VoteString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndMyVote(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVoteDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVoteDetails(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("GetVoteDetails", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetVoteDetails(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetVoteDetails", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetVoteDetails(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteVote", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteVote(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal MessageId As String) As String
            Dim results() As Object = Me.Invoke("DeleteVote", New Object() {UserId, PasswordChallenge, MessageId})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDeleteVote(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal MessageId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteVote", New Object() {UserId, PasswordChallenge, MessageId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDeleteVote(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
