'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace AddressBookService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AddressBookServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class AddressBookService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/AddressBookService/AddressBookService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadAddressBook", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadAddressBook(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("LoadAddressBook", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginLoadAddressBook(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoadAddressBook", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLoadAddressBook(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreAddressBook", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StoreAddressBook(ByVal UserID As String, ByVal PasswordChallenge As String, ByVal AddressBookString As String) As String
            Dim results() As Object = Me.Invoke("StoreAddressBook", New Object() {UserID, PasswordChallenge, AddressBookString})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStoreAddressBook(ByVal UserID As String, ByVal PasswordChallenge As String, ByVal AddressBookString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StoreAddressBook", New Object() {UserID, PasswordChallenge, AddressBookString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStoreAddressBook(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
