'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace SendMsgService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SendMessageServiceSoap", [Namespace]:="http://www20.brinkster.com/madhuprasanna/SendMessageService/")>  _
    Public Class SendMessageService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/SendMessageService/SendMessageService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/SendMessageService/SendMessage", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal ReceiverId As String, ByVal Message As String) As String
            Dim results() As Object = Me.Invoke("SendMessage", New Object() {SenderId, ChallengePass, ReceiverId, Message})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal ReceiverId As String, ByVal Message As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendMessage", New Object() {SenderId, ChallengePass, ReceiverId, Message}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/SendMessageService/SendTimedMessage", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendTimedMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal ReceiverId As String, ByVal Message As String, ByVal DT As String) As String
            Dim results() As Object = Me.Invoke("SendTimedMessage", New Object() {SenderId, ChallengePass, ReceiverId, Message, DT})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendTimedMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal ReceiverId As String, ByVal Message As String, ByVal DT As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendTimedMessage", New Object() {SenderId, ChallengePass, ReceiverId, Message, DT}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendTimedMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/SendMessageService/SendGroupMessage", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendGroupMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal GroupId As String, ByVal Message As String) As String
            Dim results() As Object = Me.Invoke("SendGroupMessage", New Object() {SenderId, ChallengePass, GroupId, Message})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendGroupMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal GroupId As String, ByVal Message As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendGroupMessage", New Object() {SenderId, ChallengePass, GroupId, Message}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendGroupMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/SendMessageService/SendGroupTimedMessage"& _ 
"", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/SendMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendGroupTimedMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal GroupId As String, ByVal Message As String, ByVal DT As String) As String
            Dim results() As Object = Me.Invoke("SendGroupTimedMessage", New Object() {SenderId, ChallengePass, GroupId, Message, DT})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendGroupTimedMessage(ByVal SenderId As String, ByVal ChallengePass As String, ByVal GroupId As String, ByVal Message As String, ByVal DT As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendGroupTimedMessage", New Object() {SenderId, ChallengePass, GroupId, Message, DT}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendGroupTimedMessage(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
