'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace RegistrationService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RegistrationServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class RegistrationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/RegistrationService/RegistrationService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Register(ByVal FN As String, ByVal LN As String, ByVal UserId As String, ByVal SN As String, ByVal DOB As String, ByVal Email As String, ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("Register", New Object() {FN, LN, UserId, SN, DOB, Email, Password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginRegister(ByVal FN As String, ByVal LN As String, ByVal UserId As String, ByVal SN As String, ByVal DOB As String, ByVal Email As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Register", New Object() {FN, LN, UserId, SN, DOB, Email, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRegister(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Remove(ByVal UserId As String) As String
            Dim results() As Object = Me.Invoke("Remove", New Object() {UserId})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginRemove(ByVal UserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Remove", New Object() {UserId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRemove(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
