'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace AuthService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AuthServiceSoap", [Namespace]:="http://www20.brinkster.com/madhuprasanna/AuthService/")>  _
    Public Class AuthService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/AuthService/AuthService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/AuthService/TestConnection", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestConnection(ByVal TestString As String) As String
            Dim results() As Object = Me.Invoke("TestConnection", New Object() {TestString})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTestConnection(ByVal TestString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TestConnection", New Object() {TestString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTestConnection(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/AuthService/ChallengeRequest", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChallengeRequest(ByVal UserId As String) As String
            Dim results() As Object = Me.Invoke("ChallengeRequest", New Object() {UserId})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginChallengeRequest(ByVal UserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChallengeRequest", New Object() {UserId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndChallengeRequest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/AuthService/Authenticate", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Authenticate(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("Authenticate", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAuthenticate(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Authenticate", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAuthenticate(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/AuthService/CloseSession", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/AuthService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CloseSession(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("CloseSession", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginCloseSession(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CloseSession", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCloseSession(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
