'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace ReqMsgService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReceiveMessageServiceSoap", [Namespace]:="http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/")>  _
    Public Class ReceiveMessageService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ReceiveMessageService/ReceiveMessageService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/AsyncMessageReques"& _ 
"t", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AsyncMessageRequest(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("AsyncMessageRequest", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAsyncMessageRequest(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AsyncMessageRequest", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAsyncMessageRequest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/SyncMessageRequest"& _ 
"", RequestNamespace:="http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/", ResponseNamespace:="http://www20.brinkster.com/madhuprasanna/ReceiveMessageService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SyncMessageRequest(ByVal UserId As String, ByVal PasswordChallenge As String) As String
            Dim results() As Object = Me.Invoke("SyncMessageRequest", New Object() {UserId, PasswordChallenge})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSyncMessageRequest(ByVal UserId As String, ByVal PasswordChallenge As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SyncMessageRequest", New Object() {UserId, PasswordChallenge}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSyncMessageRequest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
